### ISSUE TITLE
Reorganize project and configuration structure

### ISSUE THREAD

**Issue by rax845163** [containers-ai/alameda#120]
**Is your feature request related to a problem? Please describe.**

For extand project conveniently, current project struct needs reorganizing.

**Describe the solution you'd like**

Place each component's source code under its folder.( Ex: code associate with component "operator" place under alameda/operator )

**Comment by mamafun** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> For extand project conveniently, current project struct needs reorganizing.
> 
> **Describe the solution you'd like**
> 
> Place each component's source code under its folder.( Ex: code associate with component "operator" place under alameda/operator )

@rax845163  I think right now this repo is already structured as what you described in your expected solution. Please help check and close this issue if no other concerns. Thank you.
