### ISSUE TITLE
Datahub: InfluxDB database initialization

### ISSUE THREAD

**Issue by rax845163** [containers-ai/alameda#237]
**Is your feature request related to a problem? Please describe.**

There might need a routine to setup requirement InfluxDB internal databases, so even when there is no record in InfluxDB  still can client of Datahub sending query request and get empty response with status "OK".

**Describe the solution you'd like**

Add function to setup dependent resources.

**Comment by mamafun** [comment]
@rax845163 
In my memory, right now the datahub component will create an internal database if a query it received and the query hits error says no database existed. 
So if datahub can catch this exception and return empty result with "OK" status to client, this issue should be considered resolved. What about do you think?

**Comment by rax845163** [comment]
@mamafun 
Sure, we can detect this response from InfluxDB and return empty response with status code "OK" to Datahub client.

**Comment by mamafun** [comment]
tested and passed
