### ISSUE TITLE
Operator: dependent resources synchronization

### ISSUE THREAD

**Issue by rax845163** [containers-ai/alameda#238]
**Is your feature request related to a problem? Please describe.**

Before Operator start reconciling kubernetes resources, Operator might needs synchronizing the existing "AlamedaScaler" with it depentdent resources ( register/deregister pods and nodes need to be predict to/from Datahub , and existing AlamedaRecommendation in kubernetes can find associate pods' that need to be predict).

**Describe the solution you'd like**

Add routine to handle dependent resources synchronization.

**Comment by mamafun** [comment]
List scenarios that need to be tested to make sure registered pods and nodes synced to the cluster current status.

for pod:
- when an alamedascaler is created, new selected pods are registered?
- when an alamedascaler is deleted, the selected pods are de-registered?
- when a deployment/deploymentconfig/replicaset resource is created, if it is selected by an alamedascaler, the selected pods are registered?
- when a deployment/deploymentconfig/replicaset resource is deleted, if it is selected by an alamedascaler, the selected pods are de-registered?
- when alameda-operator is starting,  sync registered pods equals current selected pods by alamedescaler?

for node:
- when alameda-operator is starting,  sync registered nodes equals current cluster nodes?
- node deleted -> alameda-operator de-register this node?
- node added -> alameda-operator register this node?

@rax845163 Please comment if I miss anything. Thank you.

**Comment by mamafun** [comment]
Tested and passed
