### ISSUE TITLE
Operator: restrict workload controller monitor by one AlamedaScaler

### ISSUE THREAD

**Issue by rax845163** [containers-ai/alameda#239]
**Is your feature request related to a problem? Please describe.**

Workload controllers (Deployment and DeploymentConfig) should be monitored by one AlamedaScaler.

**Describe the solution you'd like**

Step1: Add labels in workload controller(Deployment, DeploymentConfig, etc.) to identify which AlamedaScaler needs monitoring this workload controller. Reconcile function of workload controller should appends labels in workload controllers and then update to kubernetes.

Step2: In order to get pods monitored by AlamedaScaler, function to reconcile AlamedaScaler might lists workload controllers in the current namespace which have labels that match AlamedaScaler.Spec.Selector  and the identity of AlamedaScaler that append in step2.

**Comment by mamafun** [comment]
@rax845163 
In my memory, we had committed codes to handle this situation. Could you explain current design that how we deal with pods that are selected by more than one AlamedaScaler?
Thanks.

**Comment by rax845163** [comment]
@mamafun 
Currently we create a ValidatingWebhookConfiguration to intercept below types of requests to k8s api-server.
1. CREATE and UPDATE alamedascalers.autoscaling.containers.ai.v1alpha1
2. CREATE and UPDATE deployments.extensions.v1beta1
3. CREATE and UPDATE deploymentconfigs.apps.openshift.io.v1 

Intercepting type 1 requests above, the webhook server will analyze if the deployments and deploymentconfigs that will be selected by this AlamedaScaler has been selected by other AlamedaScalers, if it does, the server will response  validate error to the api-server to block user's request.
Intercepting type 2 and 3 requests above, the webhook server will analyze if the deployments or deploymentconfigs will be selected by at most one AlamedaScaler, if not, the server will response  validate error to the api-server to block user's request.

**Comment by mamafun** [comment]
tested and passed
