### ISSUE TITLE
Operator,Datahub: output log to file 

### ISSUE THREAD

**Issue by rax845163** [containers-ai/alameda#240]
**Is your feature request related to a problem? Please describe.**

To preserve log message, output log message to file 

**Describe the solution you'd like**

To let user adjust the log file path, add log file path in configuration file.

**Comment by mamafun** [comment]
Set logfile destination to /var/log/ for all components including
- alameda-operator
- alameda-datahub
- alameda-evictioner
- alameda-adm-ctrl
