### ISSUE TITLE
Datahub: meaning of memory usage in api ListPodMetrics response 

### ISSUE THREAD

**Issue by rax845163** [containers-ai/alameda#253]
**Is your feature request related to a problem? Please describe.**

Meaning of memory usage in api ListPodMetrics response is the amount of usage core rather than cpu usage percentage.

**Describe the solution you'd like**

Define new element in enumerator MetricsType for container memory usage.

**Comment by mamafun** [comment]
@rax845163 could you update the status of this issue? Thanks.

**Comment by rax845163** [comment]
@mamafun 
Currently, MetricsType in api ListPodMetrics response is keep using CPU_USAGE_SECONDS_PERCENTAGE to represent container cpu usage millcores.

If we need to define new MetricType to represent cpu usage millcores and modify response of ListPodMetrics, the client of Datahub must be nofitied the change.

**Comment by mamafun** [comment]
@linkhsiehx @imhd 
This issue is about the term "CPU_USAGE_SECONDS_PERCENTAGE " is not right because we use cpu usage milicores as the unit.
This is one place we can do to refactor the datahub code.
