### ISSUE TITLE
Add the commit template to encourage high-quality

### ISSUE THREAD

**Issue by containers-ai-user** [containers-ai/alameda#26]
**Describe the solution you'd like**
- prompt some information for user
- e.g. Signed-off-by: username <username@email>

**Additional context**
Reference:
- https://gist.github.com/lacion/2977117#file-git-commit-template
- https://gist.github.com/adeekshith/cd4c95a064977cdc6c50

**Comment by tsungming** [comment]
The commit template should be defined on dev host. This issued is moved to [wiki](https://github.com/containers-ai/alameda/wiki/The-commit-template)
