### ISSUE TITLE
Change the base images in Dockerfile

### ISSUE THREAD

**Issue by tsungming** [containers-ai/alameda#375]
1. Using Red Hat Universal Base Images

**Comment by tsungming** [comment]
example:

https://github.com/operator-framework/operator-sdk/blob/master/images/scorecard-proxy/Dockerfile

**Comment by blueranger** [comment]
**Description of the change:**
Changing base image to <code>registry.access.redhat.com/ubi7-dev-preview/ubi-minimal</code>

**Motivation for the change:**
Upon Red Hat's request

**Comment by tsungming** [comment]
The builder's image registry.access.redhat.com/devtools/go-toolset-1.10-rhel7:1.10.3-15 can not be got

**Comment by tsungming** [comment]
@HungoHung 

I add Dockerfile.ubi for each component on release-0.3 branch.
The ubi base image will be used for OperatorHub release announce.

**Comment by mamafun** [comment]
Several commits addressed this issue and after commit aaa150e0331f465b9a5b299f342989d60f7e8ea3, this issue enters verifying stage.
(Right now all ubi images are using registry.access.redhat.com/ubi8-dev-preview/ubi-minimal:**8.0**)

**Comment by mamafun** [comment]
All the Alameda components are with a Dockerfile.ubi which uses ubi base image.
Closing this issue.
