### ISSUE TITLE
admission-controller can not fetch valid recommendations after evictioner evicts pod

### ISSUE THREAD

**Issue by rax845163** [containers-ai/alameda#382]
Create AlamedaScaler to monitor Deployment with label run = resource-consumer.
 <img width="1383" alt="Screen Shot 2019-04-08 at 6 03 02 PM" src="https://user-images.githubusercontent.com/2918565/55716037-936b8680-5a28-11e9-8731-cc600597f04c.png">

Setting containers resource field empty under Deployment's PodTemplate, Evictioner will evicts pod cause containers don't have configured request or limit after listing pod recommendations from Datahub.
<img width="1034" alt="Screen Shot 2019-04-08 at 5 59 33 PM" src="https://user-images.githubusercontent.com/2918565/55715921-4daebe00-5a28-11e9-9507-67d3be641249.png">

After evicting pods, Admission-Controller fetch no valid pod recommendations from Datahub(all pod recommendations are expired), so it bypassing the admission-request from kubernetes api-server. Remaining the containers' resource limit to be empty, Evictioner will do pod eviction again in its next process routine.

Below is recommendations in InfluxDB.
<img width="1123" alt="Screen Shot 2019-04-08 at 5 31 53 PM" src="https://user-images.githubusercontent.com/2918565/55715977-6dde7d00-5a28-11e9-8d78-06d6f2e1439f.png">

Needs to solve the time elapse between Ecvictioner's and Admisstion-Controller's routine.

**Comment by mamafun** [comment]
@kfdev170707  an idea is not to evict pod where recommendation valid period is too short.
any thought?
