### ISSUE TITLE
CPU limits and requests recommendation should NOT be 0

### ISSUE THREAD

**Issue by HungoHung** [containers-ai/alameda#445]
**To Reproduce**
1. Open nginx category sample
2. Add alamedascaler for this namespace
3. Wait and check recommendation.

**Expected behavior**
CPU limits and requests recommendation should NOT be 0

**Environment:**
OpenShift 3.11
Alameda 0.3.8-5
Alameda-AI 0.3.8-5

**Additional context**
In InfluxDB:
name,time,end_time,initial_resource_limit_cpu,initial_resource_limit_memory,initial_resource_request_cpu,initial_resource_request_memory,name,namespace,pod_name,resource_limit_cpu,resource_limit_memory,resource_request_cpu,resource_request_memory,start_time,top_controller_kind,top_controller_name
container,2019-05-02T09:52:00Z,1556790870,**0.610275**,8028159,0.1096781,8028159,nginx-example,nginx,nginx-example-1-bfgtx,**0.610275**,8028378,**0.17916940434415884**,8028378,1556790720,DeploymentConfig,nginx-example

In "oc get alamedarecommendation -o yaml":

  spec:
    containers:
    - name: nginx-example
      resources:
        limits:
          cpu: "0"
          memory: "8028378"
        requests:
          cpu: "0"
          memory: "8028378"

**Comment by linkhsiehx** [comment]
The unit of CPU should use milliCPU, because datahub will be converted it to int when updating resource recommendation.

**Comment by linkhsiehx** [comment]
Datahub is modified to use round up integer when returning CPU metric to predict on commit [https://github.com/containers-ai/alameda/commit/e9fee41a42b6ec6f9c9ca4e5d798518b11d8ff94](https://github.com/containers-ai/alameda/commit/e9fee41a42b6ec6f9c9ca4e5d798518b11d8ff94).

**Comment by HungoHung** [comment]
Verified on alameda v0.3.27
