### ISSUE TITLE
First time import dashboard JSON got "Cluster Health, Node Health and Prediction in folder 'alameda' has the same uid"

### ISSUE THREAD

**Issue by jeantung** [containers-ai/alameda#446]
**Describe the bug**

**To Reproduce**

**Expected behavior**

First time install FederatorAI-operator, it should not has existed imported dashboard JSON.

**Screenshots**

![image](https://user-images.githubusercontent.com/38522441/57119645-782d3600-6d9e-11e9-9ff6-878632fd393c.png)
![image](https://user-images.githubusercontent.com/38522441/57119649-7bc0bd00-6d9e-11e9-811c-93198583d2ec.png)
![image](https://user-images.githubusercontent.com/38522441/57119652-7ebbad80-6d9e-11e9-80a2-cd2b08af3ac6.png)

**Environment:**

**Additional context**

**Comment by mamafun** [comment]
@jeantung 
may I know how to you deploy this grafana? Is it by federatorai-operator or others?
and according to the error message, you are going to import a dashboard with an uid that is already taken by a dashboard in alameda folder. Can you double check if there are dashboards of the same uid in alameda folder?

**Comment by HungoHung** [comment]
federatorai-operator do create three dashboards under alameda folder like below:

<img width="827" alt="Screen Shot 2019-05-03 at 4 50 23 PM" src="https://user-images.githubusercontent.com/5344010/57127663-ba1ca300-6dc3-11e9-8c68-451c934b5954.png">
<img width="828" alt="Screen Shot 2019-05-03 at 4 50 12 PM" src="https://user-images.githubusercontent.com/5344010/57127669-bdb02a00-6dc3-11e9-91d0-9f54db09cdee.png">

**Comment by HungoHung** [comment]
Close the issue.
