### ISSUE TITLE
Alameda-Operator has too less memory resource, causing OOMKilled very often

### ISSUE THREAD

**Issue by jeantung** [containers-ai/alameda#447]
**Describe the bug**

![image](https://user-images.githubusercontent.com/38522441/57119761-2f29b180-6d9f-11e9-8248-23399441aa13.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/38522441/57119773-48326280-6d9f-11e9-8122-f0587bcd7cf7.png)

**Environment:**

alameda-operator version: v0.3.8-5
**Additional context**

**Comment by mamafun** [comment]
@jeantung 
how did you deploy this pod? is it by federatorai-operator or ?

**Comment by jeantung** [comment]
Yes, by federatorai-operator.

**Comment by mamafun** [comment]
@jeantung 
move the discussion to https://github.com/containers-ai/federatorai-operator/issues/133
and close this one. 
thanks
