### ISSUE TITLE
Alameda-ai.log has Message "Write recommendation result" of monitored pod's CPU, but no CPU recommendation value in database at the time point

### ISSUE THREAD

**Issue by jeantung** [containers-ai/alameda#456]
[Actual Results]
Got message "Write recommendation result" of monitored pod's CPU, but no value on "resource_limit_cpu" and "resource_request_cpu" in alameda_recommendation database, but recommendation for memory is working fine.

`2019-05-03 02:57:34,965 INFO recommendation Write recommendation result: {'pod_recommendations': [{'namespaced_name': {'namespace': 'spark-cluster-1', 'name': 'spark-cluster-w-1-zfl4r'}, 'apply_recommendation_now': True, 'start_time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:11:30Z', 'container_recommendations': [{'name': 'spark-cluster-w', 'request_recommendations': [{'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:00:00Z', 'num_value': '556173721.554072'}, {'time': '2019-05-03T03:00:00Z', 'end_time': '2019-05-03T03:03:30Z', 'num_value': '556173721.5540721'}, {'time': '2019-05-03T03:03:30Z', 'end_time': '2019-05-03T03:06:00Z', 'num_value': '556173721.5255119'}, {'time': '2019-05-03T03:06:00Z', 'end_time': '2019-05-03T03:08:30Z', 'num_value': '556173721.525512'}, {'time': '2019-05-03T03:08:30Z', 'end_time': '2019-05-03T03:11:30Z', 'num_value': '556173721.525512'}]}, {'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:00:00Z', 'num_value': '1.7405869376389955'}, {'time': '2019-05-03T03:00:00Z', 'end_time': '2019-05-03T03:03:30Z', 'num_value': '1.719962671518938'}, {'time': '2019-05-03T03:03:30Z', 'end_time': '2019-05-03T03:06:00Z', 'num_value': '1.7296659004726502'}, {'time': '2019-05-03T03:06:00Z', 'end_time': '2019-05-03T03:08:30Z', 'num_value': '1.7894782677058718'}, {'time': '2019-05-03T03:08:30Z', 'end_time': '2019-05-03T03:11:30Z', 'num_value': '1.7308123638266575'}]}], 'limit_recommendations': [{'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:00:00Z', 'num_value': '556173721.5540721'}, {'time': '2019-05-03T03:00:00Z', 'end_time': '2019-05-03T03:03:30Z', 'num_value': '556173721.5540721'}, {'time': '2019-05-03T03:03:30Z', 'end_time': '2019-05-03T03:06:00Z', 'num_value': '556173721.525512'}, {'time': '2019-05-03T03:06:00Z', 'end_time': '2019-05-03T03:08:30Z', 'num_value': '556173721.525512'}, {'time': '2019-05-03T03:08:30Z', 'end_time': '2019-05-03T03:11:30Z', 'num_value': '556173721.5255121'}]}, {'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:00:00Z', 'num_value': '1.7928314438417645'}, {'time': '2019-05-03T03:00:00Z', 'end_time': '2019-05-03T03:03:30Z', 'num_value': '1.8162212082546336'}, {'time': '2019-05-03T03:03:30Z', 'end_time': '2019-05-03T03:06:00Z', 'num_value': '1.7695840120400246'}, {'time': '2019-05-03T03:06:00Z', 'end_time': '2019-05-03T03:08:30Z', 'num_value': '1.8235953773519264'}, {'time': '2019-05-03T03:08:30Z', 'end_time': '2019-05-03T03:11:30Z', 'num_value': '1.8139310870712946'}]}], 'initial_request_recommendations': [{'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}, {'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}], 'initial_limit_recommendations': [{'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}, {'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}]}], 'top_controller': {'namespaced_name': {'namespace': 'spark-cluster-1', 'name': 'spark-cluster-w'}, 'kind': 'DEPLOYMENTCONFIG'}, 'assign_pod_policy': {'time': '2019-05-03T02:58:00Z', 'node_name': 'jeokd311-11130'}}, {'namespaced_name': {'namespace': 'spark-cluster-1', 'name': 'spark-cluster-m-1-pxxgd'}, 'apply_recommendation_now': True, 'start_time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:11:00Z', 'container_recommendations': [{'name': 'spark-cluster-m', 'request_recommendations': [{'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:11:00Z', 'num_value': '751569250.4986386'}]}, {'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:11:00Z', 'num_value': '2.3715910243356797'}]}], 'limit_recommendations': [{'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:11:00Z', 'num_value': '751569250.4986386'}]}, {'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:11:00Z', 'num_value': '2.371692951004756'}]}], 'initial_request_recommendations': [{'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}, {'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}], 'initial_limit_recommendations': [{'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}, {'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}]}], 'top_controller': {'namespaced_name': {'namespace': 'spark-cluster-1', 'name': 'spark-cluster-m'}, 'kind': 'DEPLOYMENTCONFIG'}, 'assign_pod_policy': {'time': '2019-05-03T02:58:00Z', 'node_name': 'jeokd311-11129'}}, {'namespaced_name': {'namespace': 'spark-cluster-1', 'name': 'spark-cluster-w-1-4mkb9'}, 'apply_recommendation_now': True, 'start_time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:11:00Z', 'container_recommendations': [{'name': 'spark-cluster-w', 'request_recommendations': [{'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:03:00Z', 'num_value': '836597358.3538574'}, {'time': '2019-05-03T03:03:00Z', 'end_time': '2019-05-03T03:05:30Z', 'num_value': '836597358.3291655'}, {'time': '2019-05-03T03:05:30Z', 'end_time': '2019-05-03T03:08:00Z', 'num_value': '836597358.3291655'}, {'time': '2019-05-03T03:08:00Z', 'end_time': '2019-05-03T03:11:00Z', 'num_value': '836597358.3291655'}]}, {'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:03:00Z', 'num_value': '1.9450564967228388'}, {'time': '2019-05-03T03:03:00Z', 'end_time': '2019-05-03T03:05:30Z', 'num_value': '1.805340894314223'}, {'time': '2019-05-03T03:05:30Z', 'end_time': '2019-05-03T03:08:00Z', 'num_value': '2.014089828108391'}, {'time': '2019-05-03T03:08:00Z', 'end_time': '2019-05-03T03:11:00Z', 'num_value': '2.0230788316022994'}]}], 'limit_recommendations': [{'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:03:00Z', 'num_value': '836597358.3538574'}, {'time': '2019-05-03T03:03:00Z', 'end_time': '2019-05-03T03:05:30Z', 'num_value': '836597358.3291655'}, {'time': '2019-05-03T03:05:30Z', 'end_time': '2019-05-03T03:08:00Z', 'num_value': '836597358.3291655'}, {'time': '2019-05-03T03:08:00Z', 'end_time': '2019-05-03T03:11:00Z', 'num_value': '836597358.3291655'}]}, {'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:03:00Z', 'num_value': '2.2958307240504543'}, {'time': '2019-05-03T03:03:00Z', 'end_time': '2019-05-03T03:05:30Z', 'num_value': '1.8964329608401302'}, {'time': '2019-05-03T03:05:30Z', 'end_time': '2019-05-03T03:08:00Z', 'num_value': '2.1819131850653304'}, {'time': '2019-05-03T03:08:00Z', 'end_time': '2019-05-03T03:11:00Z', 'num_value': '2.300532317503583'}]}], 'initial_request_recommendations': [{'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}, {'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}], 'initial_limit_recommendations': [{'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}, {'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}]}], 'top_controller': {'namespaced_name': {'namespace': 'spark-cluster-1', 'name': 'spark-cluster-w'}, 'kind': 'DEPLOYMENTCONFIG'}, 'assign_pod_policy': {'time': '2019-05-03T02:58:00Z', 'node_name': 'jeokd311-11129'}}, {'namespaced_name': {'namespace': 'spark-cluster-1', 'name': 'spark-cluster-w-1-52n5z'}, 'apply_recommendation_now': True, 'start_time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:09:30Z', 'container_recommendations': [{'name': 'spark-cluster-w', 'request_recommendations': [{'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:00:00Z', 'num_value': '763044336.3751048'}, {'time': '2019-05-03T03:00:00Z', 'end_time': '2019-05-03T03:02:30Z', 'num_value': '763128320.2905315'}, {'time': '2019-05-03T03:02:30Z', 'end_time': '2019-05-03T03:06:00Z', 'num_value': '763441256.5432159'}, {'time': '2019-05-03T03:06:00Z', 'end_time': '2019-05-03T03:09:30Z', 'num_value': '763489732.2364222'}]}, {'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:00:00Z', 'num_value': '1.849327995698219'}, {'time': '2019-05-03T03:00:00Z', 'end_time': '2019-05-03T03:02:30Z', 'num_value': '1.8684497871423813'}, {'time': '2019-05-03T03:02:30Z', 'end_time': '2019-05-03T03:06:00Z', 'num_value': '1.818103258900804'}, {'time': '2019-05-03T03:06:00Z', 'end_time': '2019-05-03T03:09:30Z', 'num_value': '1.830389090264898'}]}], 'limit_recommendations': [{'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:00:00Z', 'num_value': '763044336.3751048'}, {'time': '2019-05-03T03:00:00Z', 'end_time': '2019-05-03T03:02:30Z', 'num_value': '763128320.2905315'}, {'time': '2019-05-03T03:02:30Z', 'end_time': '2019-05-03T03:06:00Z', 'num_value': '763441256.5432159'}, {'time': '2019-05-03T03:06:00Z', 'end_time': '2019-05-03T03:09:30Z', 'num_value': '763489732.2364222'}]}, {'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:00:00Z', 'num_value': '1.8672231434256243'}, {'time': '2019-05-03T03:00:00Z', 'end_time': '2019-05-03T03:02:30Z', 'num_value': '1.896342901981716'}, {'time': '2019-05-03T03:02:30Z', 'end_time': '2019-05-03T03:06:00Z', 'num_value': '1.8559799856575252'}, {'time': '2019-05-03T03:06:00Z', 'end_time': '2019-05-03T03:09:30Z', 'num_value': '1.9181872405626972'}]}], 'initial_request_recommendations': [{'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}, {'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}], 'initial_limit_recommendations': [{'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}, {'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '1970-01-01T00:00:00Z', 'num_value': '0.0'}]}]}], 'top_controller': {'namespaced_name': {'namespace': 'spark-cluster-1', 'name': 'spark-cluster-w'}, 'kind': 'DEPLOYMENTCONFIG'}, 'assign_pod_policy': {'time': '2019-05-03T02:58:00Z', 'node_name': 'jeokd311-11129'}}, {'namespaced_name': {'namespace': 'spark-cluster-1', 'name': 'spark-cluster-w-1-kbk6s'}, 'apply_recommendation_now': True, 'start_time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:10:00Z', 'container_recommendations': [{'name': 'spark-cluster-w', 'request_recommendations': [{'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:10:00Z', 'num_value': '1.3618670423817183'}]}, {'metric_type': 'MEMORY_USAGE_BYTES', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:10:00Z', 'num_value': '825771195.5106008'}]}], 'limit_recommendations': [{'metric_type': 'CPU_USAGE_SECONDS_PERCENTAGE', 'data': [{'time': '2019-05-03T02:57:30Z', 'end_time': '2019-05-03T03:10:00Z', 'num_value': '1.5506045459183633'}]}, {'metric_type': 'MEMOR`

[Environment]
Openshift cluster master: 172.31.11.129; root/password; GUI login: root/password
Openshift node: 172.31.11.130; root/password
federatorai-operator version: 0.1.0
alameda-ai version: v0.3.8-5
alameda-operator version: v0.3.8-5

![image](https://user-images.githubusercontent.com/38522441/57130665-c6592e00-6dcc-11e9-83e7-a4596e0bd9ee.png)

![image](https://user-images.githubusercontent.com/38522441/57130671-c9ecb500-6dcc-11e9-8c60-70e082f3d500.png)

**Comment by containers-ai-user** [comment]
Closed
