### ISSUE TITLE
[BUG] datahub crash and get restarted after running several hours

### ISSUE THREAD

**Issue by HungoHung** [containers-ai/alameda#467]
Env:
federatorai-operator 0.2.2 + alameda 0.3.9
172.31.5.206

Result:
datahub crash and get restarted after running several hours

datahub log:
oc logs -f alameda-datahub-d9c55854d-79pmd --previous:

2019-05-22T18:23:44.402287Z	info	transport: http2Server.HandleStreams failed to read frame: read tcp 10.129.0.29:50050->10.130.0.15:50742: read: connection reset by peer
2019-05-22T18:23:44.402360Z	info	transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2019-05-22T18:23:44.625412Z	info	transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2019-05-22T18:23:44.864019Z	info	transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2019-05-22T18:23:45.021328Z	info	transport: loopyWriter.run returning. connection error: desc = "transport is closing"
panic: interface conversion: interface {} is nil, not json.Number

goroutine 965738 [running]:
github.com/containers-ai/alameda/datahub/pkg/repository/influxdb/recommendation.(*ContainerRepository).queryRecommendation(0xc000629ad8, 0xc00067e4d0, 0xa4, 0x0, 0x0, 0x0, 0xc2, 0xc00078a9c0)
	/go/src/github.com/containers-ai/alameda/datahub/pkg/repository/influxdb/recommendation/container.go:390 +0x381d
github.com/containers-ai/alameda/datahub/pkg/repository/influxdb/recommendation.(*ContainerRepository).ListContainerRecommendations(0xc000629ad8, 0xc00078a9c0, 0x0, 0x0, 0xc000629ae0, 0x40ddd8, 0x50, 0x1349e40, 0xc00060a201)
	/go/src/github.com/containers-ai/alameda/datahub/pkg/repository/influxdb/recommendation/container.go:314 +0x465
github.com/containers-ai/alameda/datahub/pkg/dao/recommendation/impl.(*Container).ListPodRecommendations(0xc00050bd10, 0xc00078a9c0, 0x0, 0x0, 0x0, 0x0, 0x96, 0x147ef20, 0x167f8c0)
	/go/src/github.com/containers-ai/alameda/datahub/pkg/dao/recommendation/impl/container.go:31 +0xcb
github.com/containers-ai/alameda/datahub.(*Server).ListPodRecommendations(0xc0003cbea0, 0x1665380, 0xc000446c60, 0xc00078a980, 0xc0003cbea0, 0xc000446bd0, 0x131a060)
	/go/src/github.com/containers-ai/alameda/datahub/server.go:712 +0x153
github.com/containers-ai/alameda/vendor/github.com/containers-ai/api/alameda_api/v1alpha1/datahub._DatahubService_ListPodRecommendations_Handler(0x147ef20, 0xc0003cbea0, 0x1665380, 0xc000446c60, 0xc00050bcc0, 0x0, 0x0, 0x0, 0xc000043cc0, 0x32)
	/go/src/github.com/containers-ai/alameda/vendor/github.com/containers-ai/api/alameda_api/v1alpha1/datahub/server.pb.go:2082 +0x241
github.com/containers-ai/alameda/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000580600, 0x16743e0, 0xc0007c5200, 0xc0007c8f00, 0xc000514960, 0x228d5e0, 0x0, 0x0, 0x0)
	/go/src/github.com/containers-ai/alameda/vendor/google.golang.org/grpc/server.go:935 +0x433
github.com/containers-ai/alameda/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000580600, 0x16743e0, 0xc0007c5200, 0xc0007c8f00, 0x0)
	/go/src/github.com/containers-ai/alameda/vendor/google.golang.org/grpc/server.go:1139 +0xd61
github.com/containers-ai/alameda/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004b9dc0, 0xc000580600, 0x16743e0, 0xc0007c5200, 0xc0007c8f00)
	/go/src/github.com/containers-ai/alameda/vendor/google.golang.org/grpc/server.go:683 +0x9f
created by github.com/containers-ai/alameda/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/containers-ai/alameda/vendor/google.golang.org/grpc/server.go:681 +0xa1

**Comment by HungoHung** [comment]
Seen on many test machines with build 0.3.11

**Comment by jasonhuangprophet** [comment]
verified
