### ISSUE TITLE
[BUG][Grafana] Need to add more condition when query alameda_prediction after alameda 0.3.10

### ISSUE THREAD

**Issue by HungoHung** [containers-ai/alameda#474]
alameda, alameda-ai 0.3.10

<img width="1551" alt="Screen Shot 2019-05-24 at 2 15 00 PM" src="https://user-images.githubusercontent.com/5344010/58306589-8961e380-7e2e-11e9-8ca2-eeaee4e99d13.png">

<img width="1398" alt="Screen Shot 2019-05-24 at 2 13 59 PM" src="https://user-images.githubusercontent.com/5344010/58306597-8e269780-7e2e-11e9-81df-65c7e5959c5e.png">

Expected:
May need to add and "kind"='raw' in query language.

<img width="1447" alt="Screen Shot 2019-05-24 at 2 14 07 PM" src="https://user-images.githubusercontent.com/5344010/58306619-a4345800-7e2e-11e9-806f-09b5e147542b.png">

**Comment by mamafun** [comment]
fixed in https://github.com/containers-ai/federatorai-operator/commit/6e1199576b4d41afe82f05e6559e70cfd4b943ca
and https://github.com/containers-ai/alameda/commit/e1e5251cdb37b0c96291bf483cf6ff5033691cac

**Comment by HungoHung** [comment]
Verified on alameda 0.3.11
