### ISSUE TITLE
There is no memory lower_bound "30" and "3600" queries in prediction doshboard on grafana

### ISSUE THREAD

**Issue by jeantung** [containers-ai/alameda#491]
**To Reproduce**
Go to Alameda-grafana GUI-->Prediction and Recommendation dashboard, right click "Container Memory ..." to edit to check queries.

**Screenshots**

![Image 6](https://user-images.githubusercontent.com/38522441/58690744-d90b5680-83bc-11e9-8025-359f5ca6fb7e.png)

**Environment:**
OKD master: 172.31.12.27 
node: 172.31.12.28
alamedaservice version: 0.3.16

**Comment by mamafun** [comment]
This should be fixed in https://github.com/containers-ai/alameda/commit/49160f4d24dc941e67093e70b1272f9256f04f44

**Comment by jeantung** [comment]
Verified.
