### ISSUE TITLE
Suggestion: applying recommendation only integer value for displaying Memory value better on OKD GUI

### ISSUE THREAD

**Issue by jeantung** [containers-ai/alameda#508]
**Describe the solution you'd like**
It could only apply integer value of recommendation to avoid displaying "Memory: 620525158400 mB to 620525158400 mB " on OKD GUI.

![Image 14](https://user-images.githubusercontent.com/38522441/58942675-cc1da700-87b0-11e9-87d4-581bbd510c11.png)
![Image 15](https://user-images.githubusercontent.com/38522441/58942676-cc1da700-87b0-11e9-8052-d7dd44be359e.png)

**Environment**
OKD master: 172.31.5.206
federator-operator version: v0.2.8
alameda version: 0.3.20

**Comment by jasonhuangprophet** [comment]
I think it still needs to fix quickly. otherwise it will shows bad image to customer.
