### ISSUE TITLE
Both CPU and memory latest observation time point are faster than current time

### ISSUE THREAD

**Issue by jeantung** [containers-ai/alameda#520]
**Describe the bug**
Current time "date" is "Mon Jun 10 17:24:34 CST 2019", but monitored pod's CPU and memory latest observation time point are faster == "17:28"

**Screenshots**

![Image 1](https://user-images.githubusercontent.com/38522441/59186830-78db9800-8ba6-11e9-9634-f6d7fa2c14b9.png)
![Image 2](https://user-images.githubusercontent.com/38522441/59186831-79742e80-8ba6-11e9-8d52-5220233639ee.png)
![Image 3](https://user-images.githubusercontent.com/38522441/59186833-79742e80-8ba6-11e9-9703-032ccc89136b.png)

**Environment:**
OKD master: 172.31.12.29
alameda version: 0.3.25

**Comment by mamafun** [comment]
fixed in commit 96025e6ae503791f905ac7eb91b572b711aef627

**Comment by jasonhuangprophet** [comment]
verified
