### ISSUE TITLE
Alameda could store initial_resource_cpu and initial_resource_mem for recommendation using later

### ISSUE THREAD

**Issue by jeantung** [containers-ai/alameda#522]
**Describe the solution you'd like**
Prometheus-k8s '--storage.tsdb.retention=15d', all pods' init cpu and memory value would be erased after 15 days, so Alameda could store initial_resource_cpu and initial_resource_mem by itself for recommendation using later.

![Image 12](https://user-images.githubusercontent.com/38522441/59249603-bea46900-8c57-11e9-8947-5ac3dd99846f.png)

**Comment by HungoHung** [comment]
Jean, as discussed, we will reserve initial values of pod if it ever exist in recommendation record. Please help to verify it. Thank you.
