### ISSUE TITLE
Alameda grafana could remove a managed object from hpa page when its scalingTools is changed

### ISSUE THREAD

**Issue by jeantung** [containers-ai/alameda#524]
**Describe the bug**
Alameda-grafana could remove a managed object form hpa page when its scalingTools is changed from hpa to vpa.

**To Reproduce**
Monitoring nginx with scalingTools: hpa, after mins, change its scalingTools to vpa.

**Screenshots**

![Image 18](https://user-images.githubusercontent.com/38522441/59321969-cb33ca80-8d06-11e9-9215-77d585eeca1d.png)
![Image 19](https://user-images.githubusercontent.com/38522441/59321970-cbcc6100-8d06-11e9-8ade-0a2f713ee6dd.png)

**Environment:**
OKD master: 172.31.7.180
federatorai-operator: 0.2.11
alameda version: 0.3.26

**Comment by mamafun** [comment]
This requires to 
- change "top_controller_name" field in alameda_cluster_status..container measurement into tag field, or
- add field in alameda_cluster_status..controller measurement to flag controller as HPA enabled

@linkhsiehx any thoughts?

**Comment by jasonhuangprophet** [comment]
Jean, please help to verify

**Comment by jeantung** [comment]
Verified.
alameda 0.3.33
