### ISSUE TITLE
HPA monitored pod should not been displayed in VPA page

### ISSUE THREAD

**Issue by jeantung** [containers-ai/alameda#529]
**Describe the bug**
Monitored pod with scalingTools: hpa which would be displayed on both hpa and vpa page on alameda-grafana.

**Screenshots**
![Image 23](https://user-images.githubusercontent.com/38522441/59343342-3c42a480-8d3e-11e9-923d-1865c75b9ae0.png)
![Image 22](https://user-images.githubusercontent.com/38522441/59343341-3c42a480-8d3e-11e9-923c-cabb016784d0.png)

**Environment:**
OKD master: 172.31.12.29
federatorai-operator: 0.2.11
alameda version: 0.3.26

**Comment by jasonhuangprophet** [comment]
verified
