### ISSUE TITLE
[Bug]alameda-ai pod is pending when do the upgrade 

### ISSUE THREAD

**Issue by jasonhuangprophet** [containers-ai/alameda#542]
**Describe the bug**

upgrade to v0.3.29 and found the alameda-ai pod is pending as the follow error log

2019-06-17 06:19:53,576 15    ERROR    POD_prediction : Traceback (most recent call last):
  File "data_processor.py", line 99, in services.orchestra.recommendation.data_processor.DataProcessor.get_pod_current_node
IndexError: list index out of range

**To Reproduce**
1. oc edit deploy federatorai-operator -n federatorai >change version to v0.2.13
2. oc edit alamedaservice -o yaml > change version to v0.3.29
3. ecnounter this error

**Expected behavior**

**Screenshots**

**Environment:**
OKD: 172.31.5.212 root/password

**Additional context**

**Comment by kfdev170707** [comment]
fixed in alameda-ai repository

**Comment by jasonhuangprophet** [comment]
verified on v0.3.33
