### ISSUE TITLE
[design] update structure of AlamedaScaler

### ISSUE THREAD

**Issue by rax845163** [containers-ai/alameda#553]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mamafun** [comment]
The background of this design change is when Alameda is updating container's resource limit/request, there will be a moment that all replicas of a deployment/deploymentconfig are not running.
To ease this situation, we create a maxUnavailable directive to instruct Alameda that that maximum unavailable pods of a deployment can be when Alameda is update the resource limit/request.
