### ISSUE TITLE
Helm chart and example deployment crashing

### ISSUE THREAD

**Issue by Gylleus** [containers-ai/alameda#630]
**Describe the bug**
When deploying Alameda following the steps in the guide the pods keep crashing, both when deploying through the helm chart and the example Kubernetes deployment files. 

**To Reproduce**
1. Clone repository
2. Deploy prometheus and influx-db
3. Deploy Alameda deployments
4. 'kubectl get pod -n alameda' to see pods crashing and restarting

**Expected behavior**
All components start as expected.

**Screenshots**
```bash
NAME                                            READY   STATUS             RESTARTS   AGE
alameda-admission-controller-7f4b6db7b9-h6bnj   0/1     Running            1          11m
alameda-ai-dispatcher-8c6bd4879-rnxs2           0/1     CrashLoopBackOff   6          11m
alameda-alameda-ai-bcdddd9bc-qhw5w              1/1     Running            2          11m
alameda-datahub-cb4645798-7cwvl                 0/1     CrashLoopBackOff   7          11m
alameda-evictioner-74775b7c47-dxmlx             0/1     Running            0          11m
alameda-executor-7c4bcbdbdc-s97nk               0/1     Running            0          11m
alameda-grafana-855f85ff4c-5rvkx                1/1     Running            0          43m
alameda-influxdb-6f6d68fb4c-v4sqm               1/1     Running            0          45m
alameda-operator-694b8699b4-8lv48               0/1     Running            1          11m
alameda-rabbitmq-5dd69f9d7-gcjbw                1/1     Running            0          11m
alameda-recommender-c689bb4f9-nsvrs             0/1     Running            0          11m
```

**Environment:**
OS: Ubuntu 18.04
Kernel: Linux k8s-1 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Alameda version: Images from 'quay.io/prophetstor/alameda-*-ubi:latest'
Kubernetes version: v.1.14.2
Cluster type: Deployed in a VM through kubespray

**Additional context**
I was trying to go through the components one by one to see if each one was starting successfully and read to logs to see if anything went wrong. The problem seems to be that I do not get a lot of output. When looking at the logs from the `datahub` pod I only see the JSON configuration before it stops and restarts without any error message. Even when rebuilding the image with log OutputLevel "debug" I get no error.

Is this something you might have seen before or have any tips of how I can find what the error might be? I am really eager to test out Alameda and see what it can do.

**Comment by kfdev170707** [comment]
Hi @Gylleus, could you help check prometheus running status by the command `kubectl get po -n monitoring`? Thanks.

**Comment by Gylleus** [comment]
Sure:

```bash
vagrant@k8s-1:~$ kubectl get pod -n monitoring 
NAME                                                     READY   STATUS    RESTARTS   AGE
alertmanager-prometheus-prometheus-oper-alertmanager-0   2/2     Running   0          18h
prometheus-grafana-7ff4568684-r6s4k                      2/2     Running   0          18h
prometheus-kube-state-metrics-547bc887b8-pntfx           1/1     Running   0          18h
prometheus-prometheus-node-exporter-2zq22                1/1     Running   0          18h
prometheus-prometheus-node-exporter-fzqcw                1/1     Running   0          18h
prometheus-prometheus-node-exporter-q5n9l                1/1     Running   0          18h
prometheus-prometheus-oper-operator-8659745764-x4bwx     1/1     Running   0          18h
prometheus-prometheus-prometheus-oper-prometheus-0       3/3     Running   1          18h
```

I deployed prometheus through the command given in the deployment guide: `helm install stable/prometheus-operator --version 5.15.0 --name prometheus --namespace monitoring`

**Comment by kfdev170707** [comment]
Hi @Gylleus, it looks influxdb and prometheus running correctly. You can reschedule datahub pod by deleting the crashed one. If rescheduled datahub pod is still running in CrashLoopBackOff status, using `kubectl describe $(kubectl get po -o name -n alameda | grep datahub) -n alameda` can see more detail information.

**Comment by Gylleus** [comment]
So it turns out the issue was with my cluster and not Alameda. The problem was with DNS since kubelet passed the wrong DNS configuration to my pods. Sorry for the inconvenience.

**Comment by shantanuv17** [comment]
Hi, I m trying to deploying alameda using example deployment. Almost all pods are crashing.

```
alameda-admission-controller-85bcb68fb7-s5rbn   0/1     CrashLoopBackOff   7          14m
alameda-ai-5c967f58ff-7pwl4                     1/1     Running            0          22m
alameda-ai-dispatcher-6576f9f4bd-sbhmf          0/1     Running            0          14m
alameda-datahub-6f9d664c7f-ws6gf                1/1     Running            0          81m
alameda-evictioner-74775b7c47-j56pc             0/1     CrashLoopBackOff   7          15m
alameda-executor-7c4bcbdbdc-w6wh6               0/1     CrashLoopBackOff   7          15m
alameda-operator-694b8699b4-wvr8t               0/1     CrashLoopBackOff   1          4s
alameda-rabbitmq-74d479b4c5-rrqfr               1/1     Running            0          82m
alameda-recommender-c689bb4f9-zhlxg             1/1     Running            0          13m

```

kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:38:25Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Please Help, I m very new to Kubernetes
